### ISSUE TITLE
Erweiterung um Speisekarte verschiedene Bistros/Imbisse

### ISSUE THREAD

**Issue by razilein** [inpercima/mittagstisch#1]
Können vllt noch die Speisekarten verschiedener Imbisse oder Bistros erweitert werden? z.B. http://www.omachi.de/
https://victoria-pizza-leipzig.de/

**Comment by inpercima** [comment]
Die Möglichkeit der Erweiterung besteht. Der Ursprung in der App beruht jedoch auf Geschäfte mit wechselndem Angebot wie es die Kantine 3 im Tapetenwerk oder auch das PAN Lokal macht.

Nach erfolgreichem Abschluss der Testphase der beispielhaft genannten Geschäfte, können weitere Erweiterungen angenommen werden.

**Comment by inpercima** [comment]
Hinzufügen von https://www.bio-mare.com/

**Comment by inpercima** [comment]
Wie ich geschrieben habe, geht es in erster Linie mehr um die mit wechselnden Gerichten. Daher wird das Ticket geschlossen. Für Biomare wird aber ein neues Ticket erstellt.
