### ISSUE TITLE
Wochekarte for Bistro am Kanal links to docx file instead of pdf

### ISSUE THREAD

**Issue by felixoberhardt** [inpercima/mittagstisch#53]
Most probably an issue due to changes of the providing website... but anyways. I'd rather read the jpeg than downloading and opening a docx :)

**Comment by inpercima** [comment]
Thanks for this issue. Will be changed soon as possible. :)

**Comment by inpercima** [comment]
We will proceed as follows: If the document is a pdf (check only the file extension) then the known link is used, if it is not, then the preview image from the website is used.
